name: leopard_demo
description: Demonstrates how to use the leopard plugin.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  audioplayers: ^0.20.1
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  flutter_redux_dev_tools: ^0.5.2
  flutter_voice_processor: ^1.0.7
  leopard_flutter: ^1.0.3
  path_provider: ^2.0.10
  provider: ^6.0.3
  redux_dev_tools: ^0.7.0
  redux_thunk: ^0.4.0
  share_extend: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/android/leopard_params.pv
    - assets/models/ios/leopard_params.pv
    - assets/models/ios/myModel-leopard.pv
